# Generated by Django 5.1.5 on 2025-01-23 12:46

import django.db.models.deletion
import django.utils.timezone
import my_crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('current_amount', models.IntegerField(default=0)),
                ('is_old', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitive_type', models.CharField(blank=True, choices=[('days_of_week', 'days_of_week'), ('very_date', 'very_date'), ('n_days', 'n_days')], max_length=50, null=True)),
                ('n_days', models.IntegerField(default=0)),
                ('dates', models.CharField(default='', max_length=255)),
                ('days_of_week', models.CharField(default='', max_length=255)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=my_crm.models.one_year_from_now)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(default='')),
                ('is_repetitive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('incomplete', 'INCOMPLETE'), ('complete', 'COMPLETE'), ('cancelled', 'CANCELLED'), ('on_pause', 'ON_PAUSE'), ('in_process', 'IN_PROCESS')], default='incomplete', max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_events', to='my_crm.account')),
            ],
        ),
    ]
