# Generated by Django 5.1.5 on 2025-02-14 16:26

import django.db.models.deletion
import django.utils.timezone
import my_crm.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('current_amount', models.IntegerField(default=0)),
                ('is_old', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitive_type', models.CharField(blank=True, choices=[('days_of_week', 'days_of_week'), ('very_date', 'very_date'), ('n_days', 'n_days')], max_length=50, null=True)),
                ('is_repetitive', models.BooleanField(default=False)),
                ('repetition_interval_days', models.IntegerField(blank=True, null=True)),
                ('repetition_dates_of_month', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('repetition_days_of_week', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('single_event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_repetition_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_repetition_date', models.DateField(blank=True, default=my_crm.models.one_year_from_now, null=True)),
                ('doing_start_time', models.TimeField(blank=True, null=True)),
                ('doing_duration_time', models.IntegerField(blank=True, default=0, null=True)),
                ('doing_end_time', models.TimeField(blank=True, null=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('-0.01'), max_digits=10, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, default='')),
                ('event_is_active', models.BooleanField(default=True)),
                ('event_status', models.CharField(choices=[('incomplete', 'INCOMPLETE'), ('complete', 'COMPLETE'), ('cancelled', 'CANCELLED'), ('on_pause', 'ON_PAUSE'), ('in_process', 'IN_PROCESS')], default='incomplete', max_length=50)),
                ('created_at_inner_info', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_at_inner_info', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at_inner_info', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_events', to='my_crm.account')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='my_crm.moneyevent')),
            ],
        ),
    ]
