# Generated by Django 5.1.5 on 2025-01-25 15:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyevent',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('-0.01'), max_digits=10, null=True),
        ),
    ]
