# Generated by Django 5.1.5 on 2025-01-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_crm', '0002_alter_moneyevent_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyevent',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moneyevent',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
