# Generated by Django 5.1.5 on 2025-01-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_crm', '0003_moneyevent_duration_minutes_moneyevent_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneyevent',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='moneyevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
