# Generated by Django 5.1.5 on 2025-01-30 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_crm', '0004_remove_moneyevent_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyevent',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_events', to='my_crm.account'),
        ),
    ]
