# Generated by Django 5.1.5 on 2025-02-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_crm', '0005_alter_moneyevent_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyevent',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
