# Generated by Django 5.1.5 on 2025-02-03 13:42

import django.utils.timezone
import my_crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_crm', '0006_moneyevent_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyevent',
            name='dates',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='moneyevent',
            name='days_of_week',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='moneyevent',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='moneyevent',
            name='end_date',
            field=models.DateField(blank=True, default=my_crm.models.one_year_from_now),
        ),
        migrations.AlterField(
            model_name='moneyevent',
            name='n_days',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='moneyevent',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
