# Generated by Django 5.1.5 on 2025-02-03 13:44

import my_crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_crm', '0007_alter_moneyevent_dates_alter_moneyevent_days_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyevent',
            name='end_date',
            field=models.DateField(blank=True, default=my_crm.models.one_year_from_now, null=True),
        ),
    ]
