# Generated by Django 5.1.5 on 2025-02-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_crm', '0008_alter_moneyevent_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyevent',
            name='n_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='moneyevent',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
    ]
